### ISSUE TITLE
GREAT TREE ADDON FOR BLENDER EVER!!!

### ISSUE THREAD

**Issue by brothermechanic** [MaximeHerpin/modular_tree#101]
THANK YOU!!!

**Comment by ekaj2** [comment]
Maxime and I say, you are welcome for the add-on!

...but please don't open an issue for that as it clutters the development. [We have a discussion forum here to talk about this if you want to join!](https://blenderartists.org/forum/showthread.php?405377-Addon-Modular-Tree)
