### ISSUE TITLE
Icon for tree operator

### ISSUE THREAD

**Issue by MaximeHerpin** [MaximeHerpin/modular_tree#112]
It would be awesome to replace the current icon by something like that: 
![icon](https://cloud.githubusercontent.com/assets/15239308/19251001/7b2820a0-8f3d-11e6-9ae0-49ee326f8f63.png)

**Comment by ekaj2** [comment]
Alright, I can look into that! I am working on crowd master a bit, and they use a custom set of icons.

**Comment by ekaj2** [comment]
Here is the file they use to do it:

```
import os
import bpy

ICONS = 'minus_green minus_red node_tree_logo plus_green plus_yellow start_sim stop_sim ' \
        'agents reset instant_setup add_agents plug code shuffle array target setup motion dice'.split(' ')
icon_collection = {}


def register_icons():
    import bpy.utils.previews
    pcoll = bpy.utils.previews.new()
    icons_dir = os.path.join(os.path.dirname(__file__), "icons")
    for icon_name in ICONS:
        pcoll.load(icon_name, os.path.join(icons_dir, icon_name + '.png'), 'IMAGE')

    icon_collection["main"] = pcoll


def unregister_icons():
    for pcoll in icon_collection.values():
        bpy.utils.previews.remove(pcoll)
    icon_collection.clear()


def cicon(name):
    pcoll = icon_collection["main"]
    return pcoll[name].icon_id

```

It's pretty short and sweet, but think it could be done a bit better (they do use GPL 3 which is awesome).

**Comment by ekaj2** [comment]
Alright take a look :-)

Here is the file I used to make the icon:

[TREE.blend.zip](https://github.com/MaximeHerpin/modular_tree/files/520654/TREE.blend.zip)

**Comment by MaximeHerpin** [comment]
I love it !

**Comment by ekaj2** [comment]
Here are some more icon blends:

[ICONS.zip](https://github.com/MaximeHerpin/modular_tree/files/525595/ICONS.zip)
