### ISSUE TITLE
Pruning

### ISSUE THREAD

**Issue by MaximeHerpin** [MaximeHerpin/modular_tree#123]
This would consist of three things:
- Control the tree boundaries with an envelop object (very easy to do)
- Control the branch density (make branches end when there is already too many branches per unit of volume)
- Create a "fight for light", meaning using a sun lamp to control areas of the tree where the growth is stimulated.

For the last two I think the best way would be to store density and illumination data in a 3d list, each voxel containing the probability of all branches in it to survive.

It shouldn't be difficult, but I'm afraid it will affect the computation time quite a lot, especially the third one.

**Comment by ekaj2** [comment]
As was mentioned before, I think our worst bottleneck will be uvs so if you can beat those, you're fine. Of course, it will be something the user can leave off until the finally steps of generation which would make it much less of a performance prob...

**Comment by MaximeHerpin** [comment]
I might add the fight for light option some day, but not now. The rest works fine.
