### ISSUE TITLE
Grease Pencil Trunk Bug

### ISSUE THREAD

**Issue by ekaj2** [MaximeHerpin/modular_tree#125]
Index out of range error if the step size is set too high:

Traceback (most recent call last):
  File "/Users/ek/Library/Application Support/Blender/2.78/scripts/addons/modular_tree/generator_operators.py", line 50, in execute
    create_tree(scene.cursor_location)
  File "/Users/ek/Library/Application Support/Blender/2.78/scripts/addons/modular_tree/tree_creator.py", line 1107, in create_tree
    grease_dir = grease_points[curr_grease_point+1] - grease_points[curr_grease_point]
IndexError: list index out of range

location: <unknown location>:-1

**Comment by ekaj2** [comment]
It all depends on the size of the grease pencil stroke as well.

**Comment by MaximeHerpin** [comment]
It happens when the length of points is 6

**Comment by ekaj2** [comment]
Yes, but if you set the step size low enough, it doesn't...even with 6 gp verts.

**Comment by MaximeHerpin** [comment]
The number of gp points doesn't matters, the rehash function creates a set of points over the gp stroke, these points are placed at a constant interval (step size). when the step size is high enough there can only be 5 points created by the rehash function ( geometric length of gp stroke divided by step size <= 5) then an error occurs.

**Comment by ekaj2** [comment]
I see. Can you fix?

**Comment by MaximeHerpin** [comment]
Done.

**Comment by MaximeHerpin** [comment]
Do you still get an error ?

**Comment by ekaj2** [comment]
No, looks fine. I will setup for a release...
