### ISSUE TITLE
New uv unwrapping system

### ISSUE THREAD

**Issue by MaximeHerpin** [MaximeHerpin/modular_tree#134]
There is a way to unwrap manually with bmesh without using the unwrap operator. It will allow the uvs to be much cleaner, and will probably reduce the computation time.

**Comment by ekaj2** [comment]
Very cool. I have played with bmesh, but not for unwrapping. I'll be very interested in your implementation.

**Comment by MaximeHerpin** [comment]
Tests indicates that this new method is very fast, taking less than 1/10 of the total tree creation time.

**Comment by ekaj2** [comment]
Interesting answer...looks like it is applicable to tree unwrapping for sure: https://blender.stackexchange.com/a/79338/28015

**Comment by MaximeHerpin** [comment]
Wow, thank's a lot !
