### ISSUE TITLE
Grid size not respected when using grease pencil

### ISSUE THREAD

**Issue by ekaj2** [MaximeHerpin/modular_tree#137]
The grid size property for batch tree generation has no effect for using grease pencil. The trees get generated at the origin of the GP stroke. This should either be disabled in the UI, or it should do a post transformation of the trees.

**Comment by MaximeHerpin** [comment]
I think it is not very useful to batch trees if they all have the same trunk, so I removed the option to di so if the grease pencil option in activated.
