### ISSUE TITLE
tutorials - leaves

### ISSUE THREAD

**Issue by catafest** [MaximeHerpin/modular_tree#139]
I try some features but I'm block at leaves. 
Where I can find some video tutorials?

**Comment by ekaj2** [comment]
Please ask such questions [here](https://blenderartists.org/forum/showthread.php?405377-Addon-Modular-Tree) if you don't mind. To answer your question, Maxime and I haven't made any and I don't know of anyone else making any. Please refer to the docs for now for most questions. For adding leaves, I will try to post something here sometime if Maxime doesn't beat me to it. Merry Christmas!
