### ISSUE TITLE
Obstacle Non-Applied Position 

### ISSUE THREAD

**Issue by ekaj2** [MaximeHerpin/modular_tree#15]
If you add an obstacle then hit update it doesn't seem to take it into account.

Please fix on release-1.0 branch again or just close this if you don't think its important.

**Comment by MaximeHerpin** [comment]
It seems to works for me, did you applied the transform and scale of the obstacle ?

However the obstacle avoidance is made as if the scale, position and rotation of the trees are as default, it may be good to change that.

**Comment by ekaj2** [comment]
Ok, didn't know the *position* had to be applied...changed this to an enhancement.
