### ISSUE TITLE
Tree creation using the blender node editor

### ISSUE THREAD

**Issue by MaximeHerpin** [MaximeHerpin/modular_tree#150]
The tree creation panel is a bit messy as there are a lot of properties. The process of creating a tree is very step based (configure the roots then the trunk the n the branches...) so a more visual workflow can be less overwhelming.

The node editor is perfect to do so.
The user can choose to use the toolbar panel or just select a node tree to work with.

The nodes will be:
• Roots , the first node.
• Trunk
• branches
• Modifiers (gravity, forces, pruning...)
• Tree output
• Inputs (radius based, iteration based or constants using a curve node)

This will allow much more simplicity while giving the opportunity to control all the parameters.

**Comment by ekaj2** [comment]
This sounds great...do you plan on adding a separate node category like Sverchok?

**Comment by MaximeHerpin** [comment]
Yes, it is much more clear that way.

**Comment by ekaj2** [comment]
You are doing great! I had no idea how to build a new node tree type...would you like any help with the node project?

**Comment by MaximeHerpin** [comment]
Done, more functionalities will be added over time.
