### ISSUE TITLE
Blender 2.79 error 

### ISSUE THREAD

**Issue by EntusBrutalus** [MaximeHerpin/modular_tree#159]
Hello, 
I have an error in the blender version 2.79 is a fix for this bug online

> Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\modular_tree\generator_operators.py", line 49, in execute
    alt_create_tree(self, scene.cursor_location)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\modular_tree\tree_creator.py", line 1929, in alt_create_tree
    node_tree = bpy.data.node_groups[mtree_props.node_tree]
KeyError: 'bpy_prop_collection[key]: key "" not found'

location: <unknown location>:-1

**Comment by tom-james-watson** [comment]
I'm seeing the same error :(

**Comment by tom-james-watson** [comment]
If you turn off 'use node workflow' you can get around the error.

**Comment by frederico4d** [comment]
Same happened to me, and the use node workflow works too, thanks!

**Comment by MaximeHerpin** [comment]
Since I am rewriting the whole addon, the issue will be solved in the next release (which will hopefully come soon).

**Comment by tom-james-watson** [comment]
Great! Thanks for the awesome addon, it's much appreciated.
