### ISSUE TITLE
Addon

### ISSUE THREAD

**Issue by b91b** [MaximeHerpin/modular_tree#165]
Impossible de cocher l'addon sur Blender User Preferences.
Indique des erreurs python

**Comment by b91b** [comment]
Voilà ce que j'ai
![capture du 2018-10-21 10-46-27](https://user-images.githubusercontent.com/19393197/47264855-cc697a80-d51e-11e8-864b-94bb9067a77d.png)

**Comment by danwipf** [comment]
open in Terminal:

ruby -e “$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)”
brew install python3
brew install numpy --with-python3
brew install git
