### ISSUE TITLE
Modular tree not compatible with blender-2.80.0-git.e5e885d0ecb9-windows64

### ISSUE THREAD

**Issue by CarlosCidrais** [MaximeHerpin/modular_tree#168]
Got the following traceback when trying to load the add-on with blender-2.80.0-git.e5e885d0ecb9-windows64

Traceback (most recent call last):
  File "D:\Blender\blender-2.80.0-git.e5e885d0ecb9-windows64\2.80\scripts\modules\addon_utils.py", line 377, in enable
    raise Exception(f"Add-on '{module_name:s}' has not been upgraded to 2.8, ignoring")
Exception: Add-on 'modular_tree-master' has not been upgraded to 2.8, ignoring

**Comment by MaximeHerpin** [comment]
You downloaded the master branch, which is the state of the last release for blender 2.79.
If you want to test the 2.8 compatible version (which is under development ) you must download the blender_28 branch (https://github.com/MaximeHerpin/modular_tree/tree/blender_28)
