### ISSUE TITLE
Blender 2.80 crash when you assign bark material to the tree (macOS 10.13.6)

### ISSUE THREAD

**Issue by Oxervision** [MaximeHerpin/modular_tree#170]
Hi,
I'm testing the add-on on Blender 2.80 & macOS 10.13.6 and works fine but I found a problem when you try to assign the bark material (added with "_append materials_" button) to the tree, Blender closes unexpectedly.

**Comment by MaximeHerpin** [comment]
Does this still happen ?
If so, is there an error message ?

**Comment by Oxervision** [comment]
Hi, the first I'm a beginner in Blender.
The assignment of materials works now, the bark material is rendered fine with Cycles in the viewport but when I change to LookDev mode, Blender crash. Other case when Blender crash is if I try to check Auto Update with the tree active.
More questions:
**1.** The Leaf Size (twig node) doesn't work
**2.** How can I set the wind parameters? 
**3.** I created a materials custom file with more leafs and I changed the twig_node file to include them, the materials have .png files, when open the materials.blend file directly in Blender the materials render fine (the alpha channel works) but when I choose my custom leaf through twig node the material is tansparent totally. What am I doing wrong? Remember, I'm a Blender's beginner
Can you check the file and tell me what's wrong?

When Blender crash it appears  a macOS error message,  I attach the materials file and the crash error file:
[Crash Error.zip](https://github.com/MaximeHerpin/modular_tree/files/2865017/Crash.Error.zip)
[Materials.zip](https://github.com/MaximeHerpin/modular_tree/files/2865014/Materials.zip)

Regards,

Óscar

**Comment by Oxervision** [comment]
This is the macOS auto update error message file:
[Auto Update Crash.zip](https://github.com/MaximeHerpin/modular_tree/files/2865048/Auto.Update.Crash.zip)

**Comment by Oxervision** [comment]
When you create a new twig node and you execute it, the node creates a new material of the leaf selected but if you change the twig parameters (without change the leaf type) with twig selected in the viewport and you push execute again it adds a new material with an incremental sufix (see the attachment image), is this normal?

![twig duplicated materials](https://user-images.githubusercontent.com/46649474/52856106-cc236980-3123-11e9-9e4e-c6d1c3c9093a.jpg)

**Comment by MaximeHerpin** [comment]
Fixed in the latest version, procedural materials will be reintroduced at some point !
