### ISSUE TITLE
Hand drawing 

### ISSUE THREAD

**Issue by elkhalafy** [MaximeHerpin/modular_tree#171]
Hello 

May you support hand-drawing like speedtree software?  

Or if you can create new add-on that focus on hand-drawing for blender 2.80 ? 

I hope watch speedtree hand drawing videos to understand me 

Thanks

**Comment by MaximeHerpin** [comment]
Done !

**Comment by elkhalafy** [comment]
Thank you.  Great job.

**Comment by elkhalafy** [comment]
It's by node or what 

May you explain in video to show to us
