### ISSUE TITLE
Trunk with Roots throws error when during Final tree creation.

### ISSUE THREAD

**Issue by HolySmokesBatman** [MaximeHerpin/modular_tree#172]
Trying to do a Final tree creation with a Trunk and Roots throws an error.  As shown in the second picture.  Just changing to Final causes the tree creation to throw an error.  It's not necessary to have the branch node in there - just a Trunk and Root node will do it.
![modular tree bug pic 001](https://user-images.githubusercontent.com/14896388/52526188-06938f00-2c6a-11e9-83fe-1453b84f724c.png)
![modular tree bug pic 002](https://user-images.githubusercontent.com/14896388/52526191-0c897000-2c6a-11e9-8d67-c832c98c3df7.png)

**Comment by MaximeHerpin** [comment]
Fixed !
