### ISSUE TITLE
[Suggestion]Let the branches cross the trunk

### ISSUE THREAD

**Issue by actcathorse** [MaximeHerpin/modular_tree#173]
This addon is the great one I have ever used.
Now I am using it to make the trees in the game,but I have encountered some minor problems.
I have to manually adjust the intersection of the trunk and the branches.
I wonder if there is a parameter that can control the intersection distance between the trunk and the branches.
That will be Prefect.
Looking forward to good news.

![tree_issue](https://user-images.githubusercontent.com/9032468/52543958-b2fb7f80-2de8-11e9-9874-96fa7620a022.jpg)

**Comment by filibis** [comment]
You should use Final for your output.
![image](https://user-images.githubusercontent.com/26340322/52544733-a9135580-2dc3-11e9-861b-daebaef1157e.png)

**Comment by actcathorse** [comment]
Hello filibis,
Because i making tree for game , so i need lowpoly tree and strip UV for  branches .
Tree in preview mode is good for game .

**Comment by MaximeHerpin** [comment]
Done !

**Comment by actcathorse** [comment]
Sorry MaximeHerpin ,
I see tree_node.py update , but i do not know how to use .
Thank your answer.

**Comment by actcathorse** [comment]
It is Great. Thank MaximeHerpin. ^_^
