### ISSUE TITLE
Error with Twig node in Blender 2.8

### ISSUE THREAD

**Issue by riccardogiorato** [MaximeHerpin/modular_tree#176]
Hello Maxime and thank you for the great addon I'm loving it!
I found out this bug when using the latest version of your plugin with the nightly build of 2.8.

I post here the error message hoping to help you out to fix this bug.
I have never modified an addon for blender but I think that it would be great for me to start fixing small bugs in your plugin to help you out.

![image](https://user-images.githubusercontent.com/4527364/53393269-34800f80-399c-11e9-92eb-271770da25a2.png)

Another problem I have is with the name of the custom nodes.
![image](https://user-images.githubusercontent.com/4527364/53393463-b96b2900-399c-11e9-83bb-e8065d04714d.png)

Can I rename and submit a pull request with the "tree parameters" node renamed to "Tree Output", it would be more consistent with the naming of the shaders nodes.

**Comment by MaximeHerpin** [comment]
Fixed in latest version ! Twig generation will be reintroduced
