### ISSUE TITLE
Undo with auto_update enabled (for Blender 2.8)

### ISSUE THREAD

**Issue by marcopavanello** [MaximeHerpin/modular_tree#177]
Congratulations and thank you for your amazing addon! it is really helping us to make a short film with trees.
There is an issue i'm getting: i create a tree in the Mtree Node Tree using some nodes and then the Tree parameters node, and i enabled auto_update in that node.
The issue is that when i change a parameter on the other nodes and then i click CTRL+Z for undo, the Tree parameters node seems to loose track of the tree, so i have to recreate it.

**Comment by MaximeHerpin** [comment]
Thanks, it should be fixed in the latest version !
