### ISSUE TITLE
Unable to load addon with the latest blender 2.8 build

### ISSUE THREAD

**Issue by tcmburt** [MaximeHerpin/modular_tree#178]
Awesome addon!  Much appreciated!
Here is the error I am getting.
![install error](https://user-images.githubusercontent.com/7064412/54768587-d975bd00-4bd5-11e9-8750-d4b813e2da67.png)

**Comment by enzyme69** [comment]
Are you using the 2.80 branch of this addon? It works for me, on Mac.

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
