### ISSUE TITLE
Unable to load addon blender 2.79 linux mint

### ISSUE THREAD

**Issue by ghostsofviikki** [MaximeHerpin/modular_tree#179]
Hi thank you very much for the addon. It works fine on windows. Linux mint version doesn't seem to work for me. Here's the error message. I can install the addon but this error pops up when I try to enable it. Please if you have time I would really appreciate it if you could address this issue.
![Screenshot from 2019-04-02 22-47-52](https://user-images.githubusercontent.com/49210349/55431570-90d8df00-5599-11e9-8fb0-50b039b22724.png)

**Comment by MaximeHerpin** [comment]
Should be fixed in the latest version !
