### ISSUE TITLE
nodes not showing up

### ISSUE THREAD

**Issue by carmandale** [MaximeHerpin/modular_tree#180]
I have installed the add-on, but nothing shows up when I am in blender. it does show a warning of upgrade of 2.8x required. I have tried with the latest version of 2.8 on Mac and PC

**Comment by carmandale** [comment]
it works in 2.79b, but I can't get it to work in 2.8. When I load the plugin, I see this message "upgrade to 2.8x required" I am using 2.80 2019-04-11

**Comment by macio97** [comment]
![Screenshot](https://user-images.githubusercontent.com/8861988/58384900-09cc4400-7fe9-11e9-9c57-b19f160cec7b.jpg)
You have to download the branch for Blender 2.8. You can close this issue task as invalid

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
