### ISSUE TITLE
Multiple crashes with the 2.8 version

### ISSUE THREAD

**Issue by scull2014** [MaximeHerpin/modular_tree#182]
Hi you probably already know this but with the latest mtree and latest blender 2.8 you get multiple random crashing. To many crashes to list them all but they vary from ticking the auto update box to crashes after editing a node and then executing. They are not all random but I say random because several times I have done the same thing twice and it has not crashed second time. This is not a complaint your addon is great and this is to be expected with the 2.8 version

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
