### ISSUE TITLE
no interface in 2.8 29-May build

### ISSUE THREAD

**Issue by rmspink** [MaximeHerpin/modular_tree#185]
Hello

The add-on is not showing up in the May 29th version of Blender 2.8.
I can see 'Modular trees' in the Tool/workspace/filter addons list, but it is not showing up as an option in Editor types.
This is where I should find the interface- correct?

Thanks
Mark
![ModularTreeProblem](https://user-images.githubusercontent.com/51241549/58719798-e30c7400-8413-11e9-9d4c-763bdf3a40d7.jpg)

**Comment by seaside98** [comment]
For 2.8 support, you need to download the zip of the [blender_28](https://github.com/MaximeHerpin/modular_tree/tree/blender_28) branch.

**Comment by BryanCrotaz** [comment]
Is this still true? If so where is the zip?

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
