### ISSUE TITLE
Modular Tree editor 

### ISSUE THREAD

**Issue by TyLuis** [MaximeHerpin/modular_tree#187]
when I installed the add-on gave this issue of update to 2.8, my version of blender is the 2.8 build of June 26
![image](https://user-images.githubusercontent.com/52267200/60230866-bc542880-986d-11e9-8be7-2ff825151205.png)

**Comment by tejaswid** [comment]
Use the branch blender_28 instead of the master branch when you download zip / clone from github.

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
