### ISSUE TITLE
Doesn't apprear to be working with Blender 2.8 latest build (6-30-19)

### ISSUE THREAD

**Issue by scott859** [MaximeHerpin/modular_tree#188]
Greetings!

Thank you for the add on but this doesn't appear to be working with Blender 2.8's latest build as of 6-30-19. Just wanted to pass along - and thanks again.

**Comment by xan2622** [comment]
Try with this branch: https://github.com/MaximeHerpin/modular_tree/tree/blender_28

It seems that Maxime hasn't merged his blender_28 branch to master yet.

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
