### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Nochefer** [MaximeHerpin/modular_tree#189]
I have version 2.8 of blender, and the add on asks me to upgrade to 2.8 and doesn't let me use it

**Comment by BryanCrotaz** [comment]
+1

**Comment by EgertKanep** [comment]
You are using wrong version then, try this - https://github.com/MaximeHerpin/modular_tree/tree/blender_28

**Comment by BryanCrotaz** [comment]
I’ve already looked at that branch but there’s no instructions of how to download it into blender.

**Comment by EgertKanep** [comment]
Just download and install zip through blender

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
