### ISSUE TITLE
Latest version not working in 2.8

### ISSUE THREAD

**Issue by Vitoria90** [MaximeHerpin/modular_tree#190]
The latest version doesn't appear to be working on Blender 2.8. I can't find any of the added features shown in the documentation.

Edit: After reinstalling three times, the tree generation part of the add-on now works, however the Tree Tools are nowhere to be found.

**Comment by xan2622** [comment]
Try with this branch: https://github.com/MaximeHerpin/modular_tree/tree/blender_28

It seems that Maxime hasn't merged his [blender_28](https://github.com/MaximeHerpin/modular_tree/tree/blender_28) branch to master yet.

**Comment by Vitoria90** [comment]
> Try with this branch: https://github.com/MaximeHerpin/modular_tree/tree/blender_28
> 
> It seems that Maxime hasn't merged his [blender_28](https://github.com/MaximeHerpin/modular_tree/tree/blender_28) branch to master yet.

That is the one I'm using. I cannot locate the Tree Tools anywhere.

**Comment by YatoAkito** [comment]
even with the f3 search bar I can't find it

**Comment by luckyllamasauce** [comment]
1. Make sure the plugin is enabled.

![1](https://user-images.githubusercontent.com/20274806/65903144-e562e880-e389-11e9-97c7-51298152d8e4.PNG)

2. Split your view and select "Mtree Node Tree" as your editor type.

3. Select New at the top and press N to bring out the tool menu if it is hidden, on the right will be Mtree.

![2](https://user-images.githubusercontent.com/20274806/65903183-f57ac800-e389-11e9-8124-18036108c195.PNG)

**Comment by vilinder** [comment]
I've tried to use it today but for no avail. I am not seeing those tabs on tool menu.
![kuva](https://user-images.githubusercontent.com/42787342/66143474-e1e09300-e60f-11e9-9bef-d3e6f83a28b1.png)

**Comment by luckyllamasauce** [comment]
Click on the button that says "New" at the top of the screenshot you provided. The tools should then become visible.

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
