### ISSUE TITLE
Button is missing for Blender version 2.8

### ISSUE THREAD

**Issue by KurtKoopa** [MaximeHerpin/modular_tree#191]
I'm not sure if I missed something here, but whenever I downloaded the file to get blender working with the extension. The button to create them isn't showing up on the menu. Is there a reason why this is happening? I've also tried downloading the older versions, but Blender isn't registering them as add ons. I've been trying to use this for two days now and even looked up some stuff about it.

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
