### ISSUE TITLE
error message says : upgrade to 2.8 x required , both for Blender 2.8 and 2.81 

### ISSUE THREAD

**Issue by emihich** [MaximeHerpin/modular_tree#192]
Modular tree does not open , because of this errorI don't know if it is a bug 
I need wind and will have to come back to blender 2.79 ?

**Comment by aidanlam** [comment]
I too am experiencing this error and confused if I am missing something. I tried both stable builds of Blender 2.8, and 2.81 (plugin version 3.0.0). System information: Microsoft Windows 10 Home Version	10.0.17763 Build 17763.

**Comment by Todderbod** [comment]
I am experiencing the same problem. When I install an add on it says must have 2.8x installed I have it installed not sure what to do to fix it

**Comment by mnhan32** [comment]
You probably downloaded it from release, which is build from master branch. You should just switch to 2.8 Branch and click Clone or download button
![mtree_2_8_download](https://user-images.githubusercontent.com/11030401/72316609-c175a980-36d1-11ea-9852-a05310e9a12b.JPG)

**Comment by emihich** [comment]
Thank you for clarifying it to me !

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
