### ISSUE TITLE
Blender 2.80 flashes "Canceling..." over and over

### ISSUE THREAD

**Issue by fletchgraham** [MaximeHerpin/modular_tree#193]
When working with a NodeTree and the Compositor at the same time, Blender acts as if it is cancelling a task over and over.

<img width="905" alt="cancelling" src="https://user-images.githubusercontent.com/7990175/67049959-6bf72400-f105-11e9-9762-454eaa6b6e6b.png">

Steps:
1. open blender 2.80
1. enable Mtree addon
1. open a compositor area and check "Use Nodes"
1. render
1. open an Mtree node editor area, and add a new NodeTree
1. in the Mtree node editor add a Trunk Node

As soon as the Trunk Node is added, the info bar at the bottom acts as if it is cancelling a job over and over, the progress bar flashing from 0% to 100% almost instantly.

If I disable the addon, the problem instantly stops.

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
