### ISSUE TITLE
2.81 log

### ISSUE THREAD

**Issue by crazyrobinhood** [MaximeHerpin/modular_tree#196]
mtree updater verbose is enabled
mtree Updater: Read in json settings from file
Warning: class MOD_TREE_OT_fast_wind contains a property which should be an annotation!
/home/nk/.config/blender/2.81/scripts/addons/modular_tree-blender_28/__init__.py:110
    assign as a type annotation: MOD_TREE_OT_fast_wind.strength
    assign as a type annotation: MOD_TREE_OT_fast_wind.speed
Warning: class MTREE_OT_connect_strokes contains a property which should be an annotation!
/home/nk/.config/blender/2.81/scripts/addons/modular_tree-blender_28/__init__.py:110
    assign as a type annotation: MTREE_OT_connect_strokes.point_dist
Warning: class mtree_node_tree contains a property which should be an annotation!
/home/nk/.config/blender/2.81/scripts/addons/modular_tree-blender_28/__init__.py:110
    assign as a type annotation: mtree_node_tree.preset_to_load
    assign as a type annotation: mtree_node_tree.preset_to_save
register_class(...):
Warning: 'mtree_settings_panel' doesn't contain '_PT_' with prefix & suffix
Warning: class MTREE_OT_save_preset contains a property which should be an annotation!
/home/nk/.config/blender/2.81/scripts/addons/modular_tree-blender_28/__init__.py:110
    assign as a type annotation: MTREE_OT_save_preset.node_group_name
    assign as a type annotation: MTREE_OT_save_preset.load
Warning: class MtreeTrunk contains a property which should be an annotation!
/home/nk/.config/blender/2.81/scripts/addons/modular_tree-blender_28/__init__.py:110
    assign as a type annotation: MtreeTrunk.seed
    assign as a type annotation: MtreeTrunk.length
    assign as a type annotation: MtreeTrunk.radius
    assign as a type annotation: MtreeTrunk.end_radius
    assign as a type annotation: MtreeTrunk.resolution
    assign as a type annotation: MtreeTrunk.shape
    assign as a type annotation: MtreeTrunk.randomness
    assign as a type annotation: MtreeTrunk.axis_attraction
    assign as a type annotation: MtreeTrunk.use_grease_pencil
Warning: class MtreeGrow contains a property which should be an annotation!
/home/nk/.config/blender/2.81/scripts/addons/modular_tree-blender_28/__init__.py:110
    assign as a type annotation: MtreeGrow.seed
    assign as a type annotation: MtreeGrow.length
    assign as a type annotation: MtreeGrow.shape_start
    assign as a type annotation: MtreeGrow.shape_end
    assign as a type annotation: MtreeGrow.shape_convexity
    assign as a type annotation: MtreeGrow.resolution
    assign as a type annotation: MtreeGrow.randomness
    assign as a type annotation: MtreeGrow.split_proba
    assign as a type annotation: MtreeGrow.split_angle
    assign as a type annotation: MtreeGrow.split_radius
    assign as a type annotation: MtreeGrow.split_flatten
    assign as a type annotation: MtreeGrow.end_radius
    assign as a type annotation: MtreeGrow.can_spawn_leafs
    assign as a type annotation: MtreeGrow.gravity_strength
    assign as a type annotation: MtreeGrow.floor_avoidance
Warning: class MtreeParameters contains a property which should be an annotation!
/home/nk/.config/blender/2.81/scripts/addons/modular_tree-blender_28/__init__.py:110
    assign as a type annotation: MtreeParameters.auto_update
    assign as a type annotation: MtreeParameters.mesh_type
    assign as a type annotation: MtreeParameters.resolution
    assign as a type annotation: MtreeParameters.create_leafs
    assign as a type annotation: MtreeParameters.leaf_amount
    assign as a type annotation: MtreeParameters.leaf_max_radius
    assign as a type annotation: MtreeParameters.leaf_dupli_object
    assign as a type annotation: MtreeParameters.leaf_size
    assign as a type annotation: MtreeParameters.leaf_extremity_only
    assign as a type annotation: MtreeParameters.leaf_spread
    assign as a type annotation: MtreeParameters.leaf_flatten
    assign as a type annotation: MtreeParameters.leaf_weight
    assign as a type annotation: MtreeParameters.create_armature
    assign as a type annotation: MtreeParameters.armature_min_radius
    assign as a type annotation: MtreeParameters.has_changed
    assign as a type annotation: MtreeParameters.active_tree_object
    assign as a type annotation: MtreeParameters.last_execution_info
Warning: class OBJECT_OT_mtree_execute_tree contains a property which should be an annotation!
/home/nk/.config/blender/2.81/scripts/addons/modular_tree-blender_28/__init__.py:110
    assign as a type annotation: OBJECT_OT_mtree_execute_tree.node_group_name
Warning: class MtreeSplit contains a property which should be an annotation!
/home/nk/.config/blender/2.81/scripts/addons/modular_tree-blender_28/__init__.py:110
    assign as a type annotation: MtreeSplit.seed
    assign as a type annotation: MtreeSplit.amount
    assign as a type annotation: MtreeSplit.split_angle
    assign as a type annotation: MtreeSplit.max_split_number
    assign as a type annotation: MtreeSplit.radius
    assign as a type annotation: MtreeSplit.start
    assign as a type annotation: MtreeSplit.end
Warning: class MtreeBranch contains a property which should be an annotation!
/home/nk/.config/blender/2.81/scripts/addons/modular_tree-blender_28/__init__.py:110
    assign as a type annotation: MtreeBranch.seed
    assign as a type annotation: MtreeBranch.advanced_settings
    assign as a type annotation: MtreeBranch.amount
    assign as a type annotation: MtreeBranch.split_angle
    assign as a type annotation: MtreeBranch.max_split_number
    assign as a type annotation: MtreeBranch.radius
    assign as a type annotation: MtreeBranch.end_radius
    assign as a type annotation: MtreeBranch.min_height
    assign as a type annotation: MtreeBranch.length
    assign as a type annotation: MtreeBranch.shape_start
    assign as a type annotation: MtreeBranch.shape_end
    assign as a type annotation: MtreeBranch.shape_convexity
    assign as a type annotation: MtreeBranch.resolution
    assign as a type annotation: MtreeBranch.randomness
    assign as a type annotation: MtreeBranch.split_proba
    assign as a type annotation: MtreeBranch.split_flatten
    assign as a type annotation: MtreeBranch.can_spawn_leafs
    assign as a type annotation: MtreeBranch.gravity_strength
    assign as a type annotation: MtreeBranch.floor_avoidance
Warning: class OBJECT_OT_mtree_twig contains a property which should be an annotation!
/home/nk/.config/blender/2.81/scripts/addons/modular_tree-blender_28/__init__.py:110
    assign as a type annotation: OBJECT_OT_mtree_twig.node_group_name
    assign as a type annotation: OBJECT_OT_mtree_twig.node_name
Warning: class MtreeTwig contains a property which should be an annotation!
/home/nk/.config/blender/2.81/scripts/addons/modular_tree-blender_28/__init__.py:110
    assign as a type annotation: MtreeTwig.seed
    assign as a type annotation: MtreeTwig.length
    assign as a type annotation: MtreeTwig.radius
    assign as a type annotation: MtreeTwig.branch_number
    assign as a type annotation: MtreeTwig.randomness
    assign as a type annotation: MtreeTwig.resolution
    assign as a type annotation: MtreeTwig.gravity_strength
    assign as a type annotation: MtreeTwig.flatten
    assign as a type annotation: MtreeTwig.leaf_object
    assign as a type annotation: MtreeTwig.leaf_type
    assign as a type annotation: MtreeTwig.leaf_size
Warning: class MTREE_OT_randomize_tree contains a property which should be an annotation!
/home/nk/.config/blender/2.81/scripts/addons/modular_tree-blender_28/__init__.py:110
    assign as a type annotation: MTREE_OT_randomize_tree.node_group_name
Warning: class MtreeRoots contains a property which should be an annotation!
/home/nk/.config/blender/2.81/scripts/addons/modular_tree-blender_28/__init__.py:110
    assign as a type annotation: MtreeRoots.seed
    assign as a type annotation: MtreeRoots.length
    assign as a type annotation: MtreeRoots.resolution
    assign as a type annotation: MtreeRoots.split_proba
    assign as a type annotation: MtreeRoots.randomness
Warning: class MTREE_OT_reset_active_tree_object contains a property which should be an annotation!
/home/nk/.config/blender/2.81/scripts/addons/modular_tree-blender_28/__init__.py:110
    assign as a type annotation: MTREE_OT_reset_active_tree_object.node_group_name
Warning: class MTREE_OT_update_gp_strokes contains a property which should be an annotation!
/home/nk/.config/blender/2.81/scripts/addons/modular_tree-blender_28/__init__.py:110
    assign as a type annotation: MTREE_OT_update_gp_strokes.node_group_name
Warning: class Preferences contains a property which should be an annotation!
/home/nk/.config/blender/2.81/scripts/addons/modular_tree-blender_28/__init__.py:110
    assign as a type annotation: Preferences.auto_check_update
    assign as a type annotation: Preferences.updater_intrval_months
    assign as a type annotation: Preferences.updater_intrval_days
    assign as a type annotation: Preferences.updater_intrval_hours
    assign as a type annotation: Preferences.updater_intrval_minutes

this probably refers to:
https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API/Addons

**Comment by Anyeos** [comment]
I don't see any recent activity on this plugin. I hope there are some developers "alive" that can come to "save us" :P

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
