### ISSUE TITLE
Node Tree does not appear

### ISSUE THREAD

**Issue by haraldlux** [MaximeHerpin/modular_tree#197]
Add-ons: Add Mesh: Modular trees upgrade to 2.8x required is stated 
and Node Tree does not appear. 
But Blender Version 2.81 (2.81 2019-11-20) is installed![Bildschirmfoto 2019-12-08 um 20 37 16](https://user-images.githubusercontent.com/58572788/70394997-c40e2080-19fa-11ea-9e7c-32682865ddf0.png)
![Bildschirmfoto 2019-12-08 um 20 35 48](https://user-images.githubusercontent.com/58572788/70395005-d4be9680-19fa-11ea-967c-75dfa348061c.png)

**Comment by Hugo-Trentesaux** [comment]
You can download the 2.8 version here : https://github.com/MaximeHerpin/modular_tree/tree/blender_28

**Comment by haraldlux** [comment]
Thank you for the link! I thought I had the 2.8 Version. But it seems I did not. Now it works!
