### ISSUE TITLE
time.clock removed in python 3.8

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [MaximeHerpin/modular_tree#198]
From the [python 3.8 changelog](https://docs.python.org/3/whatsnew/3.8.html#api-and-feature-removals): 

>The function time.clock() has been removed, after having been deprecated since Python 3.3: use time.perf_counter() or time.process_time() instead, depending on your requirements, to have well-defined behavior. (Contributed by Matthias Bussonnier in bpo-36895.)

This gives ```AttributeError: module 'time' has no attribute 'clock'``` when updating a tree.

**Comment by DoMal27** [comment]
A quick fix:
Find and replace all `time.clock()` to `time.perf_counter()`
in `~/modular_tree/nodes/tree_parameters_node.py`

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
