### ISSUE TITLE
Error when execute Twig Node in Blender 2.81a

### ISSUE THREAD

**Issue by emo10001** [MaximeHerpin/modular_tree#201]
Hello.  I'm running Blender 2.81a on Windows 10, with Mtree version 3.1.0.  Everything was working well until I added the twig node and clicked execute.  This is the error I got. 
![MTreeError](https://user-images.githubusercontent.com/39274180/73117840-21115780-3f11-11ea-9db8-7607ae364197.png)

Otherwise this is a fabulous addon!  Keep up the great work!

**Comment by emo10001** [comment]
Ok, I discovered that I only have this issue if I have the Tree parameters output set to Final.  When it's set to Preview, the twig node works just fine.

Not a big deal for me, but figured it would be something you'd like to work on.

Thanks again for a great tool!

**Comment by frnsys** [comment]
I had to do something different for this to work:

What worked for me is to first add a twig node and "execute" the node, creating a mesh called `tree`, then rename the mesh to `twig` (or whatever else). Then set up the tree nodes: a trunk node into a branch node, then a "tree parameters" node separately. Check `create_leafs`, then click the eyedropper for the `leaf` parameter and select your `twig` mesh in the scene hierarchy. Then click `execute tree`.

**Comment by MaximeHerpin** [comment]
Fixed in latest version ! Twigs generation will be reintroduced
