### ISSUE TITLE
[Feature request] Ability to animate node parameters

### ISSUE THREAD

**Issue by thima2017** [MaximeHerpin/modular_tree#204]
I need to make continuous electric lightning and I found it is possible to make it by animation of some parameters of mtree nodes. But animation doesn't work and I don't know how to fix it.
This is a duplicate of this issue [https://github.com/MaximeHerpin/modular_tree/issues/195]

**Comment by Outboarder** [comment]
Ability to animate using Drivers and keyframes in AutoUpdate mode is super useful.
Please do it, It's very fun.

**Comment by slin35** [comment]
> I need to make continuous electric lightning and I found it is possible to make it by animation of some parameters of mtree nodes. But animation doesn't work and I don't know how to fix it.
> This is a duplicate of this issue [https://github.com/[/issues/195](https://github.com/MaximeHerpin/modular_tree/issues/195)]

Did you ever figure out how to animate node parameters? I'm still looking for a solution loll

**Comment by MaximeHerpin** [comment]
This is not a priority, might be done in the future
