### ISSUE TITLE
mtree not installing on blender 2.82

### ISSUE THREAD

**Issue by mlorenzo2408** [MaximeHerpin/modular_tree#205]
Hello,
I have tried to install the latest verstion of mtree 3.1 and i get an error when I try to enable it....
cannot import name 'nodes_classes' from 'modular_tree-blender_28.nodes'

**Comment by eezacque** [comment]
On install, I get an error message "upgrade to 2.8x required" (running Blender 2.82)

**Comment by ItsmeSzark** [comment]
Did you follow the instructions? Last post https://github.com/MaximeHerpin/modular_tree/issues/192

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
