### ISSUE TITLE
Mtree crashes at 2.82

### ISSUE THREAD

**Issue by JoeeGe** [MaximeHerpin/modular_tree#211]
Hello,
Since Mtree crashes most time at the final steps, i started blender with the console and get errors, what are related to changes at the phyton api from 2.80?
A solution is here, to chance the asingment from annotations at class from "value = myvalue" to "value: my value"
https://github.com/KhronosGroup/glTF-Blender-IO/issues/147

**Comment by JoeeGe** [comment]
I had another crash today, after i tried to connect almost all nodes, and tried to make then leafs, but it only showed a memory access error, so not sure, what was the cause.
'There is another blog about the changes at the Api. 
A 'workaround of the changed code would be there
https://theduckcow.com/2019/update-addons-both-blender-28-and-27-support/

def make_annotations(cls):
    """Converts class fields to annotations if running with Blender 2.8"""
    if bpy.app.version < (2, 80):
        return cls
    bl_props = {k: v for k, v in cls.__dict__.items() if isinstance(v, tuple)}
    if bl_props:
        if '__annotations__' not in cls.__dict__:
            setattr(cls, '__annotations__', {})
        annotations = cls.__dict__['__annotations__']
        for k, v in bl_props.items():
            annotations[k] = v
            delattr(cls, k)
    return cls

**Comment by CryOns** [comment]
> I had another crash today, after i tried to connect almost all nodes, and tried to make then leafs, but it only showed a memory access violation, so not sure, what was the cause.
> 'There is another blog about the changes at the Api.
> A 'workaround' for the changed code would be there
> https://theduckcow.com/2019/update-addons-both-blender-28-and-27-support/
> 
> def make_annotations(cls):
> """Converts class fields to annotations if running with Blender 2.8"""
> if bpy.app.version < (2, 80):
> return cls
> bl_props = {k: v for k, v in cls.**dict**.items() if isinstance(v, tuple)}
> if bl_props:
> if '**annotations**' not in cls.**dict**:
> setattr(cls, '**annotations**', {})
> annotations = cls.**dict**['**annotations**']
> for k, v in bl_props.items():
> annotations[k] = v
> delattr(cls, k)
> return cls

Have you managed to solve your problem? If not, let me try to help you. Can you tell me if your pc has a graphics card?

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
