### ISSUE TITLE
No Wind options in 2.82

### ISSUE THREAD

**Issue by Rickietee** [MaximeHerpin/modular_tree#212]
There are no wind operations in Blender 2.8x versions, using the 2.8 branch... 

![image](https://user-images.githubusercontent.com/51098846/80987011-4d4e4580-8e29-11ea-92d6-73dffd6887a0.png)

**Comment by CryOns** [comment]
> There are no wind operations in Blender 2.8x versions, using the 2.8 branch...

Have you tried to activate the Advanced Settings? It is the box available at the top of the nodes, for marking, written "advanced_settings" on the side.

**Comment by MaximeHerpin** [comment]
Wind will be reintroduced as a geometry node tree
