### ISSUE TITLE
Addon nto working because blender version

### ISSUE THREAD

**Issue by magnojrdev** [MaximeHerpin/modular_tree#213]
Hi, I have Blender 2.82:
"version: 2.82 (sub 7), branch: master, commit date: 2020-03-12 05:06, hash: 375c7dc4caf4, type: Release
build date: 2020-03-12, 15:41:08
platform: Windows"
but the addon keep saying "upgrade to 2.8x required".

Can you please help me? Thanks.

**Comment by magnojrdev** [comment]
![image](https://user-images.githubusercontent.com/53837975/81295399-bbbc1f00-9046-11ea-8892-a6218fb8c632.png)

**Comment by magnojrdev** [comment]
sorry, downloaded the branch 28 and now worked. thanks.

**Comment by Rickietee** [comment]
You need to change from master branch, to 2.8 branch in the repository.

![Screenshot_20200507-134321_Chrome](https://user-images.githubusercontent.com/51098846/81295722-c5ef1500-9068-11ea-81fc-87b03d2b250a.jpg)

**Comment by johnmccraemavial** [comment]
dont install master version
direct link for blender 2.8
https://github.com/MaximeHerpin/modular_tree/tree/blender_28
