### ISSUE TITLE
Can't get Mtree to work in Blender 2.83

### ISSUE THREAD

**Issue by Nole9399** [MaximeHerpin/modular_tree#215]
I was able to use Mtree in Blender 2.82 but when I upgraded to 2.83 Mtree is not displaying in the mode window.  When I installed Mtree in 2.83 everything went well according to Blender's displays notes.  I checked the box in the addon section went to Blender but there is no Mtree in the Mode window for me to choose.  Mtree installed in appdata instead of programfiles and I moved it over to programfiles to see if that would help and it did not so I moved it back.  I have Windows 10,  Intel i7-8750h, 32ram.  Any suggestions on what I can do to get it to work?
Thanks

**Comment by Derek-K** [comment]
I tried 2.82a and 2.83 on Windows 10, Mtree node just doesn't show up. Also, it said, "upgrade to 2.8x required" ??

![image](https://user-images.githubusercontent.com/16491026/83961720-dced7680-a863-11ea-8cef-54af96b056ef.png)

**Comment by Derek-K** [comment]
@Nole9399 Hope this helps. I think the [installation instruction page](https://github.com/MaximeHerpin/modular_tree/wiki/Installation-Instructions) needed to be updated!!!

Long story short, use "blender_28" branches works for me!

![image](https://user-images.githubusercontent.com/16491026/83961926-19ba6d00-a866-11ea-9402-1bddab0f138a.png)

Direct download [link](https://github.com/MaximeHerpin/modular_tree/archive/blender_28.zip)

https://github.com/MaximeHerpin/modular_tree/issues/213#issuecomment-625232233

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
