### ISSUE TITLE
Mauvaise orientation des feuilles

### ISSUE THREAD

**Issue by Zimzim440** [MaximeHerpin/modular_tree#216]
Bonjour,
Je ne comprends pas pourquoi depuis la 2.8 je n'arrive pas à orienter les feuilles correctement avec Twig Node quand j'utilise mes propres feuilles.
Elles se positionnent à 90° par rapport à la branche.
Sincères salutations et merci pour ce que vous faites.

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
