### ISSUE TITLE
Problems with Eevee softshadows

### ISSUE THREAD

**Issue by zayca** [MaximeHerpin/modular_tree#217]
When I use mtree addon, adding new preset (tree) makes softshadows in eevee stop working

**Comment by CryOns** [comment]
> When I use mtree addon, adding new preset (tree) makes softshadows in eevee stop working

It's true, but all you need to do to have the soft shadows again is:
![1](https://user-images.githubusercontent.com/67652570/86166533-5129db80-baeb-11ea-9463-1d0e4f77210e.PNG)
![2](https://user-images.githubusercontent.com/67652570/86166542-54bd6280-baeb-11ea-8309-131190e2f6f0.PNG)

Even if you close the current M-Tree node tree, your tree will still remain in the scene and can still be modified later, just select the node tree again in the M-Tree node editor.

**Comment by MaximeHerpin** [comment]
Blender issue
