### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by juliatur12** [MaximeHerpin/modular_tree#218]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Program Files\Blender Foundation\Blender 2.83\modular_tree-blender_28\__init__.py", line 105, in register
    addon_updater_ops.register(bl_info)
  File "C:\Program Files\Blender Foundation\Blender 2.83\modular_tree-blender_28\addon_updater_ops.py", line 1405, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'addon_updater_install_popup'

**Comment by CryOns** [comment]
> Traceback (most recent call last):
> File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 382, in enable
> mod.register()
> File "C:\Program Files\Blender Foundation\Blender 2.83\modular_tree-blender_28__init__.py", line 105, in register
> addon_updater_ops.register(bl_info)
> File "C:\Program Files\Blender Foundation\Blender 2.83\modular_tree-blender_28\addon_updater_ops.py", line 1405, in register
> bpy.utils.register_class(cls)
> ValueError: register_class(...): already registered as a subclass 'addon_updater_install_popup'

It seems to have to do with the Grease Pencil recognition code of the add-on being outdated with the current Blender code. After all, the current Grease Pencil code in Blender has been rewritten from scratch.

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
