### ISSUE TITLE
Mac issue 2.8.3.1

### ISSUE THREAD

**Issue by glasscanvas** [MaximeHerpin/modular_tree#220]
does not work on MAC 2.8.3.1 wants update

**Comment by glasscanvas** [comment]
Got it working. See issue #215 on how to select the correct branch for Blender 2.8.
First uninstall the wrong branch, quit blender. Restart and install the correct branch. Don't just delete and reinstall without quitting.

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
