### ISSUE TITLE
can't use add-on with Blender 2.831 

### ISSUE THREAD

**Issue by callmeJack104** [MaximeHerpin/modular_tree#221]
I get a need to upgrade to 2.8 warning

**Comment by CryOns** [comment]
![1](https://user-images.githubusercontent.com/67652570/86163626-ed051880-bae6-11ea-8e0d-bac518bba552.PNG)
![2](https://user-images.githubusercontent.com/67652570/86163623-ebd3eb80-bae6-11ea-8c25-70470b4f324a.PNG)

**Comment by CryOns** [comment]
> I get a need to upgrade to 2.8 warning

![1](https://user-images.githubusercontent.com/67652570/86163777-1f167a80-bae7-11ea-8e5c-5c730d4aec96.PNG)
![2](https://user-images.githubusercontent.com/67652570/86163782-1faf1100-bae7-11ea-92a6-15b7f7d90665.PNG)

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
