### ISSUE TITLE
Crash on creating leafs. Mac OS Catalina 10.15.6, Blender 2.83.3

### ISSUE THREAD

**Issue by Plscall922** [MaximeHerpin/modular_tree#224]
After trying add leafs to my tree Blender crashes.

Actions that willing to crash: 
1. change amount of leafs (by default 3000, try put any number there and it will crash)
2. any attempt to put child object for leafs will crash blender.

![image](https://user-images.githubusercontent.com/40308170/88324826-890bf380-cd24-11ea-8055-a386817e936b.png)

After re-opening blender M-tree add-on always turned off.

**Comment by Plscall922** [comment]
Update. Works fine if "auto update" feature turned off.

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
