### ISSUE TITLE
Unable to create "Fat" Trees with roots Blender 2.83.3

### ISSUE THREAD

**Issue by einirpals** [MaximeHerpin/modular_tree#225]
When the trunk radis gose over 2.5 ish and the roots are somewhat complex (see pic), I'm not able to create the final tree, only the preview works.

![Screenshot_3](https://user-images.githubusercontent.com/15929776/88727612-7841f000-d11f-11ea-98be-c9d9addddf4b.png)

![Screenshot_4](https://user-images.githubusercontent.com/15929776/88727796-d1118880-d11f-11ea-8869-f188d40368dc.png)

Error message.
![Error](https://user-images.githubusercontent.com/15929776/88727794-cfe05b80-d11f-11ea-80f4-51896037b34e.png)

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
