### ISSUE TITLE
Upgrade to 2.8x required

### ISSUE THREAD

**Issue by Crafto1337** [MaximeHerpin/modular_tree#226]
It says that I must upgrade to Blender 2.8x, but I am on 2.83 already!

**Comment by Byron1c** [comment]
Im pretty sure it means the MTree Addon needs to be updated to 2.8x :(  

I find the addon still works as far as I have tried it out. Its pretty good, and I hope it either gets updated, or someone Forks this project off and does the update

**Comment by Crafto1337** [comment]
Ok, thank you very much! Upgrading the plugin to 2.8x helped

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
