### ISSUE TITLE
Mtree plugin says "upgrade to 2.8x required"

### ISSUE THREAD

**Issue by lamancuso12** [MaximeHerpin/modular_tree#227]
tried installing the latest plugin from github, version 3.0.0. I'm on Blender 2.83.3, so not sure what the issue is. The MTree mode isn't available in the dropdown menu where it should be. .

**Comment by SecretBench** [comment]
I am having the same issue with Blender 2.83.5.

**Comment by metal3d** [comment]
You should use the blender_280 branch https://github.com/MaximeHerpin/modular_tree/tree/blender_28 the click on the "code" button => download zip

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
