### ISSUE TITLE
Blender 2.83 and Blender 2.9: Modular Tree 3.0 "Upgrade to 2.8x required"

### ISSUE THREAD

**Issue by DanChristos** [MaximeHerpin/modular_tree#229]
I downloaded 'download_modular_tree3.0.0.zip' and dropped 'ch_trees' dir into my addons dir inside Blender 2.83 and 2.9. I get the problem with both:
![ModularTrees_Blender2 83](https://user-images.githubusercontent.com/64300836/92314995-28a1ee80-f012-11ea-99d0-e925e8284dbd.png)
"Upgrade to 2.8x required" message in addon preferences
M Tree editor does not show up in Editor Types list.

**Comment by antoinefortin** [comment]
Having the same problem here.

**Comment by antoinefortin** [comment]
Use the 28 branch : https://github.com/MaximeHerpin/modular_tree/tree/blender_28

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
