### ISSUE TITLE
Exporting the model as fbx/ obj

### ISSUE THREAD

**Issue by amoghgh** [MaximeHerpin/modular_tree#233]
The material nodes of the leaves, trees do not get exported in the fbx/ obj file format.
Blender version: 2.90.1

**Comment by tlalexander** [comment]
I had this issue too and just decided to use the Blender "sapling" plugin which works fine. Too bad tho as this tool is nicer to use.

**Comment by MaximeHerpin** [comment]
materials are procedural and cannot be translated to fbx or obj format, I would advise to use simpler materials with image texture if you want to export the trees.
