### ISSUE TITLE
Add Mesh MTree addon not working.

### ISSUE THREAD

**Issue by filmmakerchuck** [MaximeHerpin/modular_tree#234]
Add Mesh MTree addon not working.

**Comment by b-layer** [comment]
Don't open issues if you can't be bothered to say anything more than "not working".

**Comment by onerawartist** [comment]
@filmmakerchuck you can find videos of youtube , they way to get familiar with the addon i used the presets, choose one of the preset trees and edit it to fit your needs.

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
