### ISSUE TITLE
How to have leaves follow hair lenght/direction

### ISSUE THREAD

**Issue by MostHostLA** [MaximeHerpin/modular_tree#236]
Not really an issue, as much as a suggestion - as per documentation:
"And there is no practical way to change the hair directions with a script"
This is partially true, because it's not easy. but it's also not correct.

Follow these steps:
Make a tree.
Add leaf (a branch in my case).
You now should have the tree itself, and a particle system for the branches with leaves.
Click on the leafs and access the particle system, set Render As to None - we don't need it.

Next, duplicate (just to be safe) your branch (or leaf) that you wish to use as the instance along the path.
In Object mode - Access the Modifier's section and add a ParicleInstance modifier.
Towards the bottom of the modifier click the Create Along Paths checkbox.

You now have a tree, with a particle system you can comb and modify as needed.
Note that doing this removes the randomized rotation given by default script. I haven't found a way to preserve that, since it's imparted by the modified mesh that spawns the particles, and that creates issues.

I'm mostly using this to make a custom branch made out of branches to populate a bigger tree with.

I believe that the procedural leaf generation could be improved by using the faces of an Ngon to generate the particles. as it is, with the little tris, it's very difficult to orient the base of the leaf as you want (but you can enter edit mode and turn the tris around, even duplicate it.) it just takes a long time compared to being able to paint a hair directly onto the tree.
What you can do, is edit the mesh for the leaf particle, and extrude...

**Comment by MaximeHerpin** [comment]
Leaves scattering now uses geometry nodes so this is no longer an issue !
