### ISSUE TITLE
M-Tree Node Tree not found

### ISSUE THREAD

**Issue by PraketSD** [MaximeHerpin/modular_tree#238]
'M-Tree Node Tree' is not visible after successfully installing and activating the Add-on. 
Blender 2.90.0

![Bug Report M-Tree](https://user-images.githubusercontent.com/75920966/102002399-2d1d2800-3d22-11eb-8c4c-2e451b767b56.jpg)

**Comment by Skrigl22** [comment]
I have the addon visible in the node editor drop-down, but under 'add>nodes>' all the nodes are greyed out.

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
