### ISSUE TITLE
doesn't work with 2.91 period. 

### ISSUE THREAD

**Issue by JuanCS710** [MaximeHerpin/modular_tree#240]
it doesn't work with the latest blender 2.91 doesn't show up at all.

**Comment by cdosrunwild** [comment]
same here

**Comment by bassbum37** [comment]
The blender_28 branch works for me in 2.91, though it looks like the nodes have changed in that branch.

**Comment by flowers3030** [comment]
check out this comment on how to fix this #244 (comment)

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
