### ISSUE TITLE
Warnings with blender 2.91

### ISSUE THREAD

**Issue by DerSyl** [MaximeHerpin/modular_tree#241]
Hello,
My Blender was slow when loading and i decided to run it in cmd mode and you will see the result in the screenshot.
I'm not a good user of github. I just send this with hope it will help you !
Thank you. Bye.
![image](https://user-images.githubusercontent.com/25694589/102797060-6d7a4700-43af-11eb-9057-7f79847f451e.png)

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
