### ISSUE TITLE
warnings with Blender 2.8.3.10 (long term support version)

### ISSUE THREAD

**Issue by RichardEllicott** [MaximeHerpin/modular_tree#243]
I will try with the latest Blender

but i get an "upgrade to 2.8+" message in this version of Blender which doesn't make sense

i guess i can't expect you to solve it necessarily, maybe you just have to change the warning message. It would be cool if it could work with this version though... i use the LTS as i get overwhelmed by changes sometimes and have my own scripts that can break

EDIT: just updated from 2.8.3.7 => 2.8.3.10 as i noticed i had an older LTS version, same issue

**Comment by flowers3030** [comment]
check out this comment on how to fix this #244 (comment)

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
