### ISSUE TITLE
Modular_tree_master.zip Not Working Blender 2.90.1

### ISSUE THREAD

**Issue by Madmouser** [MaximeHerpin/modular_tree#244]
I've installed modular_tree_master.zip, from Github to Blender 2.90.1 and enabled it in Blender.  Under Editor Type, there is no editor type: Mtree Node Tree. In Blender's Preferences, Under the Add Mesh: Modular Trees addon, There is a caution sign (triangle with exclamation point) a note that says "Upgrade to 2.8x Required". This lead to my question, "is the Modular Trees addon available for Blender 2.90.1"?

**Comment by Madmouser** [comment]
Ps: Thank you for all your work. Here are some screenshots that might help.
![AddonPreferences](https://user-images.githubusercontent.com/20561763/103387005-4a8a1a00-4ab6-11eb-948b-82367e0e8228.png)
![EditorTypeWnoMtreeOption](https://user-images.githubusercontent.com/20561763/103387012-54ac1880-4ab6-11eb-8392-6e2eb9a0e511.png)

**Comment by micemincer** [comment]
You have to download from github the branch for blender 28 - not master - then it works perfectly fine ;)
![image](https://user-images.githubusercontent.com/26724189/103409497-67caf100-4b67-11eb-9774-1c587b6151b6.png)

**Comment by Madmouser** [comment]
After installing the correct version of Moduar_tree (ver. 2.8) , all works fine now. Thank you very much!

**Comment by ssjjessy** [comment]
> You have to download from github the branch for blender 28 - not master - then it works perfectly fine in 2.91 ;)
> ![image](https://user-images.githubusercontent.com/26724189/103409497-67caf100-4b67-11eb-9774-1c587b6151b6.png)

![image](https://user-images.githubusercontent.com/5580066/103610346-cfb96880-4ed4-11eb-9995-78e223af04e3.png)
I'm sorry where is the option to download the blender_28 code?

**Comment by Madmouser** [comment]
Top left corner. Under the "code" drop down.

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
