### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by PatriotTrav** [MaximeHerpin/modular_tree#246]
does not work with blender 2.9.

**Comment by gitpushoriginmaster** [comment]
Report: Error
Traceback (most recent call last):
File ".../addon_utils.py", line 351, in enable
mod = __ import__(module_name}
ModuleNotFoundError: No module named 'modular_tree_3'

**Comment by flowers3030** [comment]
check out this comment on how to fix this #244 (comment)

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
