### ISSUE TITLE
NO node tree

### ISSUE THREAD

**Issue by urazyjazzy** [MaximeHerpin/modular_tree#247]
I have the latest version of M-Tree and the latest version of blender. 2.92  After installation of the plugin via pref. install zip and enabling it there is no new editor window. I made sure that I saved the preferences and also made a full restart of the program just incase. Checked if the add-on was still seen installed and checked. Yes it was ! But still no  Tree Node editor :( 
![Screenshot (32)](https://user-images.githubusercontent.com/20549045/104118052-25f43480-5337-11eb-85f8-234f3af0f0bc.png)
![blender tree pref](https://user-images.githubusercontent.com/20549045/104118061-34425080-5337-11eb-9dfe-1f909f128dfd.JPG)

**Comment by echurley** [comment]
99% sure this is because you are using Blender 2.9x instead of 2.8x

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
