### ISSUE TITLE
VERSION BUG.

### ISSUE THREAD

**Issue by sjonU** [MaximeHerpin/modular_tree#251]
I am using Blender 2.91.2. I downloaded and installed Version 3.0.0 of your Modular Trees plug-in. I get a warning that I need to upgrade to version 2.8X. Am not sure where to go with this. Please advise.
<img width="482" alt="Screen Shot 2021-01-26 at 7 22 35 PM" src="https://user-images.githubusercontent.com/78059064/105928972-33ced880-600c-11eb-87cf-721f6c3d415e.png">

My email is sjon@sjon.org

**Comment by flowers3030** [comment]
got it,  from github, change branch/tag (Left) dropdown menu from master to blender_28. then on right green dropdown menu where it says code, click to see dropdown menu and download from here. Seems to work like this.

**Comment by MaximeHerpin** [comment]
Fixed in latest version.
