### ISSUE TITLE
This Addon Not Run Last Version

### ISSUE THREAD

**Issue by hierr0r** [MaximeHerpin/modular_tree#253]
The latest version of this plugin does not work at all in 2.9 versions, including 2.8. I have tried it in almost all versions. When I try to activate the plugin, I get a name node not found error. I think the plugin owner is no longer interested in this project.

**Comment by flowers3030** [comment]
i just found this, via a youtube video. is there a way to make it work? does tree need a certain version? and then import tree mesh to newest blender version. I really like the trees this add on pumps out, it would be a shame for this to go to waste.

**Comment by flowers3030** [comment]
got it,  from github, change branch/tag (Left) dropdown menu from master to blender_28. then on right green dropdown menu where it says code, click to see dropdown menu and download from here. Seems to work like this.

**Comment by hierr0r** [comment]
old version works fine. However, the new version cannot even be activated. It's a great add-on. This friend has done a really great job, there's almost no need for software like SpeedTree. However, there is no one yet to deal with the plugin's errors. Hopefully this fixes the issue soon. If so, I am thinking of preparing a Turkish Tutorial about this plugin.

**Comment by MaximeHerpin** [comment]
Fixed in latest version.
