### ISSUE TITLE
It works in blender 2.9x yes it does

### ISSUE THREAD

**Issue by flowers3030** [MaximeHerpin/modular_tree#255]
check out this comment on how to fix this #244 (comment)

Alot of post on here not being able to make it work, i responded to alot of them id suggest closing those tickets as solved and update a readme or something

**Comment by Erosion139** [comment]
It may work but not 100%. The wind simulators are missing for one, I have not used this addon enough to know what else is missing. But since it is annoyingly at the end of the process almost its a real shame that the quick wind and physics-based wind effects are not present.

**Comment by MaximeHerpin** [comment]
Thanks ! Fixed in latest version.
