### ISSUE TITLE
Upgrade to 2.8x

### ISSUE THREAD

**Issue by ProfAga05** [MaximeHerpin/modular_tree#256]
When I install it, it always says, that I need to upgrade blender to 2.8x, but I am already using the 2.91

**Comment by Ivanzzz1** [comment]
Hi!
It's the same with me. But the main thing is that I can't use it.

**Comment by kaancetinkayasf** [comment]
Its not working in newer versions

**Comment by MaximeHerpin** [comment]
Fixed in latest version.
