### ISSUE TITLE
still doesn't work with blender 2.91

### ISSUE THREAD

**Issue by vinishhub** [MaximeHerpin/modular_tree#257]

**Comment by gauravrai853** [comment]
> [
![103409497-67caf100-4b67-11eb-9774-1c587b6151b6](https://user-images.githubusercontent.com/58934584/109117819-806f1600-7768-11eb-9557-ad3a1c5ddc44.png)


select  blender_28 instead of master it will work fine

**Comment by vinishhub** [comment]
thanks it worked 👍
 I thought It won't work with blender 2.9
