### ISSUE TITLE
Saw some mistake BL 2.92

### ISSUE THREAD

**Issue by Marco105** [MaximeHerpin/modular_tree#260]
Hello,
I try with the version Mbtre 28 on Blender2.92 and saw message from console :
- "assign as a type annotation:" not really difficult to resolve but you have also
some class not spelling as the PY recommandation like "PT" for Panel class derived
or "OT" for Operator class derived, and so on.

Anyway this addon is well done, just some issue slow the start of the whole apps.
Thanks a lot !

**Comment by MaximeHerpin** [comment]
Thanks! Fixed in latest version.
