### ISSUE TITLE
Upgrade requirements

### ISSUE THREAD

**Issue by sjonU** [MaximeHerpin/modular_tree#262]
I am running Mesh: Modular Trees Version 3.0.0 in Blender 2.9.3 on a Macintosh running Big Sur. The add-on tells me that an "Upgrade to 2.8x required". Please tell me how to fix this. 

Thank you, 
Sjon Ueckert

**Comment by jiabaoyu** [comment]
Same here, but I'm on windows 10. Tried others method of downloading the 2.8 version. Didn't get that luck also!

**Comment by JonAimTech** [comment]
I have the same problem, hope someone can help!

**Comment by MaximeHerpin** [comment]
Fixed in latest version.
