### ISSUE TITLE
Blender 2.92

### ISSUE THREAD

**Issue by aboim2** [MaximeHerpin/modular_tree#263]
Is this addon working with Blender 2.92?

thanks

**Comment by GianniGi** [comment]
No, same problem here. Please update!

**Comment by Draise14** [comment]
Looking forward to the update.

**Comment by frnsys** [comment]
It works if you use the `blender_28` branch

**Comment by jiabaoyu** [comment]
> It works if you use the `blender_28` branch

I'm using 2.93, and it doesn't work

**Comment by JC0NN0R** [comment]
Tried on 2.91 and 2.93 and didn't work for either....gave me this error 
`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'modular_tree-3.0'`

**Comment by MaximeHerpin** [comment]
Fixed in latest version.
