### ISSUE TITLE
l'addon ne se lance pas

### ISSUE THREAD

**Issue by probox-injet** [MaximeHerpin/modular_tree#265]
Bonjour,
L'addon ne se lance pas lorsque je les télécharger sur blender, quand j'ouvre l'éditeur de noeux je ne peux pas créer les configuration pour créer un arbre, j'ai juste les configurations de base. Et je n'est pas l'onglet Mtree qui c'est créer. Et il me demande aussi de l'upgrade to 2.8x required et quand je l'installe aussi je ne peux pas l'activer.

**Comment by MaximeHerpin** [comment]
Fixed in latest version.
