### ISSUE TITLE
Persisting errors when adjusting values in Blender 2.92

### ISSUE THREAD

**Issue by onceadrog** [MaximeHerpin/modular_tree#266]
Sometimes when adjusting a value it throws this error. 
Any subsequent adjustment of anything and updating throws the same error.
![image](https://user-images.githubusercontent.com/6299372/116820940-23fbee80-ab3d-11eb-9b55-9b82e65f9f83.png)

Unable to determine source of first error, but undoing until before first error solves it.

This has happened multiple times, but now I know to undo to stop it persisting.

**Comment by kaancetinkayasf** [comment]
Almost any feature in this add-on is not working properly on newer versions of Blender.

**Comment by MaximeHerpin** [comment]
Fixed in latest version.
