### ISSUE TITLE
Can't load saved presets in Blender version 2.92.0

### ISSUE THREAD

**Issue by FlyingGoa7** [MaximeHerpin/modular_tree#267]
Starting with the default tree as a base, I made a simple tree with the trunk node connected to a split node, which finally feeds into a grow node.  I entered a name in the "save preset" box and hit "save preset."  When trying to load this preset elsewhere (new nodetree or another blend file)  I got the error below.   None of the nodes have noodles, and none of the sliders do anything when the nodes are reconnected.  Quick note: I only get this issue with custom presets, the built in ones work fine
![Screenshot (50)](https://user-images.githubusercontent.com/84039557/117866327-01688480-b265-11eb-9965-1697ee1f2a29.png)
![Screenshot (51)](https://user-images.githubusercontent.com/84039557/117866328-02011b00-b265-11eb-808e-c903a6670b33.png)

**Comment by MaximeHerpin** [comment]
Fixed in latest version. Presets will be reintroduced !
