### ISSUE TITLE
Node tree disappears from mtree editor

### ISSUE THREAD

**Issue by FlyingGoa7** [MaximeHerpin/modular_tree#268]
Using with Blender 2.92 

Not sure if this is bug or user error, but trying to google it, I couldn't find any info about this issue so I figured I'd make a post here.

After spending a good amount of time on a tree, the next time I opened the file, the tree only registers as a curve object and can no longer be edited in the mtree node editor.  The mtree node editor is empty, and no nodetrees were saved.  Luckily, I saved it as a preset so I can rebuilt it.  There's an error message when trying to load saved custom presets, which I posted about earlier, but somehow when reconnecting all the nodes, it seemed to work.  (The error with saved presets seems to just erase all the noodles between nodes and uncheck auto-update for some reason)

The only issue, however, is that trying to update the palm tree I had made (instead of creating a new tree) causes the leaves to double up.  It seems to still recognize it as an mtree--When I adjust parameters such as length or trunk shape, it updates accordingly without looking like a new tree clipping through the old one, the only problem being the the leaves doubling up. 

Quick Edit: The issue with leaves doubling up seems to be fixed now after tweaking the leaf amount and size parameters in the mtree editor

Also: .Just out of curiosity, I tried clicking the "fake user" icon for the nodetree to see if that would make it save, but again, upon closing and reopening the blend file, the nodetree was missing.  It's good that it can at least be brought back if it's been saved as a preset, but it's a little annoying to have to do every time I want to make a change such as adding branches.

**Comment by dhirajkushwaha** [comment]
I am having the same issue.

**Comment by FlyingGoa7** [comment]
> 
> 
> I am having the same issue.

Glad I'm not the only one.

**Comment by FlyingGoa7** [comment]
sorry, accidentally closed.  New to github.  Should be reopened now.

**Comment by txirrindulari** [comment]
same to me. Any work around to get the nodes back?

**Comment by MaximeHerpin** [comment]
Fixed in latest version.
