### ISSUE TITLE
Modular Trees Not Accessible 

### ISSUE THREAD

**Issue by JonAimTech** [MaximeHerpin/modular_tree#276]
I've just attempted to install Modular Trees Version 3.0.0 on Blender 2.91 and followed regular install add on procedure, however the Option to Add Mesh > Modular Trees isnt appearing. I upgraded to Blender 2.93 latest release and still no joy. 

The Add-ons window has an exclamation mark next to the Add Mesh: Modular Trees listing and says Update to 2.8X is required but im using the latest version of everything. 

See attached screen shot: 
![image](https://user-images.githubusercontent.com/86053629/122383585-de677980-cf62-11eb-8e72-6a2b33269be7.png)

Hope you can help, Many thanks,

**Comment by BriAri1** [comment]
Hello as per user Yafu try using this updated file.
https://blenderartists.org/t/modular-tree/674043/923

**Comment by MaximeHerpin** [comment]
Fixed in latest version.
