### ISSUE TITLE
Not able to download Mtree Addon

### ISSUE THREAD

**Issue by pyrup** [MaximeHerpin/modular_tree#278]
Hello everyone im trying to install the mtree, its is installing but when i go to Mtree node editor section and after i create a new material then when i go to Load preset in Mtree section. it is showing me this error...

Python: Traceback (most recent call last):
  File "C:\Users\asus\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\nodes\node_tree.py", line 216, in draw
    op.node_group_name = tree.name #set node group name as curent node tree name
AttributeError: 'MTREE_OT_save_preset' object has no attribute 'node_group_name'

location: <unknown location>:-1

Could someone pls help me out?

**Comment by MaximeHerpin** [comment]
Fixed in latest version.
