### ISSUE TITLE
mtree adddon issue

### ISSUE THREAD

**Issue by deathwalker14** [MaximeHerpin/modular_tree#279]
in blender2.93 ur addon is not working , plz helpme 
![Screenshot (2)](https://user-images.githubusercontent.com/86592654/123597898-89a0ea00-d811-11eb-90ec-2d88e4340e35.png)

**Comment by Adridri24** [comment]
The solution can be found in #281

Errors are due to changes on the Blender Python API side, try this fix:
https://blenderartists.org/uploads/short-url/jJdvhznoccp0VVqHMgzi3nfoYhe.zip

**Comment by MaximeHerpin** [comment]
Fixed with latest version.
