### ISSUE TITLE
M tree not working

### ISSUE THREAD

**Issue by bunbun205** [MaximeHerpin/modular_tree#280]
So i installed mtree from all the available branches, but it doesn't seem to work in any on them and gives the same error: 
![2021-06-29 (2)](https://user-images.githubusercontent.com/61233534/123780672-46ce2900-d888-11eb-9cff-fd9c48771efe.png)
![2021-06-29 (4)](https://user-images.githubusercontent.com/61233534/123780843-75e49a80-d888-11eb-9ef5-b5909ad23be5.png)

**Comment by VlDAL** [comment]
Same here.. Exactly the same problem. I'm assuming thi Addon needs to be updated for newer versions of Blender?

**Comment by bunbun205** [comment]
Well, I found out in earlier problems that some developer fixed the issue and I downloaded their version. It works now, but I still get error in some features.

**Comment by VlDAL** [comment]
Found the solution here: https://blenderartists.org/t/modular-tree/674043/923
Someone created a fix for it.

**Comment by MaximeHerpin** [comment]
Fixed with latest version.
