### ISSUE TITLE
Doesn't seem to work anymore.

### ISSUE THREAD

**Issue by VlDAL** [MaximeHerpin/modular_tree#281]
Trying to use this with Blender 2.93.
Shoult it work? Nothing works.. not even the "check for updates" button in the add on menu.

**Comment by VlDAL** [comment]
Someone made a fix for it here: https://blenderartists.org/t/modular-tree/674043/923

**Comment by yashmali999** [comment]
Hey thank you so much i was struglling to find how to fix the error !!
