### ISSUE TITLE
Addon not working in blender 2.93...shows only blank nodes and no presets can be loaded....hope its fixed...I use it a lot and find it very useful

### ISSUE THREAD

**Issue by Kp1330** [MaximeHerpin/modular_tree#283]
![Screenshot (7)](https://user-images.githubusercontent.com/71318863/124381589-e94f3780-dce0-11eb-8d74-4c33ca1d3cc2.png)
![Screenshot (8)](https://user-images.githubusercontent.com/71318863/124381593-ece2be80-dce0-11eb-89b6-8a2fcd18c4c4.png)
![Screenshot (9)](https://user-images.githubusercontent.com/71318863/124381602-efddaf00-dce0-11eb-93ce-b2be15ccb6e5.png)
Even tried reinstalling the add on but in vain.

**Comment by Adridri24** [comment]
The solution can be found in #281 

Errors are due to changes on the Blender Python API side, try this fix:
https://blenderartists.org/uploads/short-url/jJdvhznoccp0VVqHMgzi3nfoYhe.zip

**Comment by Nikdxmk** [comment]
> 
> 
> The solution can be found in #281
> 
> Errors are due to changes on the Blender Python API side, try this fix:
> https://blenderartists.org/uploads/short-url/jJdvhznoccp0VVqHMgzi3nfoYhe.zip

Working! Thank you )

**Comment by MaximeHerpin** [comment]
Fixed with latest version.
