### ISSUE TITLE
instal issue modular tree 

### ISSUE THREAD

**Issue by hashbb** [MaximeHerpin/modular_tree#284]
hi there ! hope you're well, I have a problem with the installation of the modular tree, I do exactly what I have to do but when I open the nodes, it written that I have to upgrade to 2.8 but when I do it, it's written there's an error "no module named 'modular tree'"

please help meeeee!!!! I have a video clip to finish in 5 days

**Comment by MaximeHerpin** [comment]
Fixed with latest version.
