### ISSUE TITLE
modualr tree

### ISSUE THREAD

**Issue by KingDynamite** [MaximeHerpin/modular_tree#286]
i can't find modular tree or tree in add/mesh/. im using 2.92
![image](https://user-images.githubusercontent.com/50347366/125111872-6ea56400-e0b4-11eb-80c1-d3b10a2fa7d5.png)

**Comment by Blenderwizard62** [comment]
The addon won't work in blender 2.9+, I regret to say that I think Development is dead, I don't have the abillaty to fix the addon.

**Comment by Masterblop** [comment]
The addon is not dead, the developer has resumed work on it.
You can check here: https://github.com/MaximeHerpin/modular_tree/tree/mtree_rework

**Comment by Blenderwizard62** [comment]
Thanks, good to know it is a good addon.

**Comment by KingDynamite** [comment]
thanks, yes it is a good addon
