### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by nitram3** [MaximeHerpin/modular_tree#287]
I installed the latest mtree rework (published 2 days ago). Blender says it installed successfully, but the addon is not visible in the add-ons tab in the blender preferences. Add-on files have appeared in the appdata folder (*user folder*\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons) however.

**Comment by officialEmmel** [comment]
same issue

**Comment by MaximeHerpin** [comment]
It should work now (only on blender 2.93), but it is an alpha so don't expect it to be feature complete or stable.
