### ISSUE TITLE
Mtree 4 isn't working now 

### ISSUE THREAD

**Issue by SlincHD** [MaximeHerpin/modular_tree#290]
well Mtree isn't working in blender 2.93.1 and i won't blame you it is still alpha so i hope that it will be fixed by reliese or even bether by beta

have a great day Slinc.
(and if there is a typo i am sory, i have dislexya D;)

**Comment by EmpireOcean** [comment]
yep, Mtree 4.0 give only remove button on board. Can you fix it please ?

**Comment by AVG1919** [comment]
ok
