### ISSUE TITLE
can anyone help, before factory reset of windows Mtree addon was working fine

### ISSUE THREAD

**Issue by luvpreet19** [MaximeHerpin/modular_tree#291]
![cherry 2](https://user-images.githubusercontent.com/88176174/127597861-b517375e-e440-4e46-bfe4-ddc5cc037d20.png)
![cherry](https://user-images.githubusercontent.com/88176174/127597864-91cc53fd-5f20-4358-8fdb-0ae197774a20.png)

**Comment by YourPainkiller** [comment]
![1111111](https://user-images.githubusercontent.com/72042447/127639289-39f448d5-bcc5-4ef4-8206-2027a490fef6.png)
the same problem, but i didnt reset Windows

**Comment by MaximeHerpin** [comment]
Fixed with latest version.
