### ISSUE TITLE
No show

### ISSUE THREAD

**Issue by Ingapambi** [MaximeHerpin/modular_tree#292]
Installed MT 3 
<img width="245" alt="Screen Shot 2021-07-30 at 5 48 24 PM" src="https://user-images.githubusercontent.com/44510383/127723513-2d7742fa-cb80-4313-879f-ef3da9a22aa9.png">
<img width="471" alt="Screen Shot 2021-07-30 at 5 48 46 PM" src="https://user-images.githubusercontent.com/44510383/127723515-8e7e7fc7-d313-485a-82e4-3a610500f868.png">
into Blender 2.93.2. I enabled it, but it doesn't show in the tools tab.

**Comment by MaximeHerpin** [comment]
Fixed with latest version.
