### ISSUE TITLE
Cannot Load preset : traceback (node_tree.py error line 162)

### ISSUE THREAD

**Issue by ashjeman** [MaximeHerpin/modular_tree#295]
I've seen tutorial and I'm sure I installed the mtree addon properly. however, when I tried to load a preset, an error popped out below:
![image](https://user-images.githubusercontent.com/66347387/130203068-7398ff80-7177-47c2-860a-aa4897d46b21.png)

**Comment by schipiga** [comment]
@ashjeman , @Tronspace you can download working version in #289
