### ISSUE TITLE
Blender 2.93.1 or 2.93.3 - MTree not working

### ISSUE THREAD

**Issue by BenMartinBox** [MaximeHerpin/modular_tree#298]
Modular Tree is not working on Blender 2.93.1 or 2.93.3.
I'm sure your are aware of that.

Are you planning to keep "advancing" and updating this wonderful add-on to work with the latest Blender version?
Also, any plans to allow the created assets (Trees) to simulate wind animation?
Appreciated.

**Comment by Abcd-Arnab-2005-github** [comment]
Hi, I also have this same problem. The nodes are showing empty in Blender for me.
![mtree addon bug](https://user-images.githubusercontent.com/89312965/131306041-1c04469f-ab1d-40f7-b9c5-e7946c6fa057.png)

**Comment by Tronspace** [comment]
> I'm on Blender 2.93.3 and it is working.
> Be sure to load it form here:
> https://github.com/schipiga/modular_tree/archive/refs/heads/blender_28.zip

Just tried again from this link, this time it worked! thank you

**Comment by BenMartinBox** [comment]
> Just tried again from this link, this time it worked! thank you

You are welcome.

**Comment by BenMartinBox** [comment]
> Hi, I also have this same problem. The nodes are showing empty in Blender for me.

Be sure to load it form here:
https://github.com/schipiga/modular_tree/archive/refs/heads/blender_28.zip

**Comment by RohanPatil1** [comment]
> I'm on Blender 2.93.3 and it is working.
> Be sure to load it form here:
> https://github.com/schipiga/modular_tree/archive/refs/heads/blender_28.zip

This worked! Thank You!

**Comment by Abcd-Arnab-2005-github** [comment]
Oh yeah, It worked from this link! 
But I found a strange behaviour. I don't know if it's specific to me, when split the window from the left side and open the node editor, it doesn't show the presets but when I open it from the right, the presets are shown perfectly.

I don't know why but it seems funny to me. 😆 (I might add a screenshot but later)

**Comment by MaximeHerpin** [comment]
Fixed with latest version.
