### ISSUE TITLE
mtree not working with blender 2.93.4-windows-x64

### ISSUE THREAD

**Issue by layan21** [MaximeHerpin/modular_tree#300]
hello, mtree addon is not working with blender 2.93.4-windows-x64 there is an error that show "Upgrade to 2.8x required
![Screenshot_1](https://user-images.githubusercontent.com/90967874/133888627-53a8682f-ada1-42e0-bbcb-b8ae7e21fb55.png)
"

**Comment by MaximeHerpin** [comment]
Fixed with latest version.
