### ISSUE TITLE
Created nodes are blank and does not work

### ISSUE THREAD

**Issue by FuckingUsernameHere** [MaximeHerpin/modular_tree#306]
Nodes does not make anything. When I create a node it has nothing in it, no parametrs. I'm a noob so don't know how to fix this... Please help.

When I try to use a node it says this:
Python: Traceback (most recent call last):
  File "C:\Users\UserName\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\nodes\trunk_node.py", line 35, in draw_buttons
    op.node_group_name = self.id_data.name # set name of node group to operator
AttributeError: 'MTREE_OT_update_gp_strokes' object has no attribute 'node_group_name'

location: <unknown location>:-1

![image](https://user-images.githubusercontent.com/67069377/138248903-6dca1b02-362e-4063-a1c0-2df422f9abb5.png)

**Comment by g-ibarra** [comment]
Same issue here. I managed to make a tree a few days ago, saved the file and tried to open it a couple of days ago and nodes are blank. I upgraded from 2.93.4 to 2.93.5, uninstalled and re-installed the add-on, same problem in my PC and my laptop
![Screenshot 2021-11-04 091708](https://user-images.githubusercontent.com/63922214/140288532-c1f29db8-148e-45cd-b17a-a0185591ee43.png)
.

**Comment by g-ibarra** [comment]
Just found a solution! Its [here ](https://github.com/MaximeHerpin/modular_tree/issues/277) Install that fix instead. Mine works now.

**Comment by MaximeHerpin** [comment]
Fixed with latest version.
