### ISSUE TITLE
installation with blender 2.92 says 'Upgrade to 2.8x required'

### ISSUE THREAD

**Issue by sneakyimp** [MaximeHerpin/modular_tree#307]
I followed the [instructions](https://github.com/MaximeHerpin/modular_tree/wiki/Installation-Instructions) and see that the Blender Preferences add-on form says "Upgrade to 2.8x required". I'm running 2.92, which is clearly far more recent than 2.8x. Is there some more up to date version? Will it work with 2.92?

**Comment by leonard7e** [comment]
Same here, if I try to install MTree 3.0.0 

MTree 3.0.0 was released 2018, around 2 years before Blender 2.93 was released.

I tried MTree 4.0.0 too, it does work with Blender 2.93

**Comment by RichardEllicott** [comment]
this repo has not had a commit for 4-5 years.... that is to be expected

u might need to look for alternatives, please let me know what you find/like

i don't personally have time to fork a repo and dev it, i assume the guy just got bored of the software, it's the way open source can go somethimes. If you don't mind, lease let me know also if there was anything you preffered about this to sapling (don't feel compelled to write an essay, just a line or two other why this was better)

thanks... hey maybe the repo owner might come back, it's a lot easier for someone to maintain their own code than for someone else to learn it

**Comment by MaximeHerpin** [comment]
the next version is actually around the corner :) 
look at the "mtree_rework" branch !

**Comment by RichardEllicott** [comment]
nice thanks

**Comment by MaximeHerpin** [comment]
Fixed in latest version
