### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by dil-lus** [MaximeHerpin/modular_tree#308]
![Blender Info Log 19_11_2021 9_31_08 pm](https://user-images.githubusercontent.com/94718404/142688011-099750b6-8af5-41a8-8de8-6e72bf7836a9.png)

Each time I try to load a present in Mtree node tab it shows the error in the picture. Is there a solution to this?

**Comment by MaximeHerpin** [comment]
Fixed with latest version
