### ISSUE TITLE
Leave distribution

### ISSUE THREAD

**Issue by xlhuillier** [MaximeHerpin/modular_tree#309]
Hello,

Congratulations and thanks ! Very good work !

I know you are working on it, and I installed and played with the 4.0.0 branch ! Great.
So far, I do not have leave distribution... May be it is on-going task.

Xav

**Comment by xlhuillier** [comment]
I do see the button. 
But I understood that the first time it generates an error. And then the Add leaves button is just not working.

Here the error on my side

![Capture d’écran de 2021-12-01 16-40-02](https://user-images.githubusercontent.com/95325645/144265316-8aa5e5b9-8b0d-4f8a-9943-b14016d41d9c.png)

**Comment by MaximeHerpin** [comment]
Does the file `geo_nodes_2_93.blend` exist in `resources/geo_node` where the addon is installed ?

**Comment by snarmo** [comment]
I have the same problem on Windows version of Blender. I'm not sure slash character should be used in definition of MTREE_RESOURCE_DIR in resource_utils.py as it's incompatible with Widows. I'm not a programmer though:-)

**Comment by MaximeHerpin** [comment]
Indeed, it should be solved now !
