### ISSUE TITLE
Add-on activation

### ISSUE THREAD

**Issue by xlhuillier** [MaximeHerpin/modular_tree#310]
Hi,

I see that you have fixed my leave distribution issue. So I download the files from the latest 4.0.0 "rework".
I have now an activation issue after add-on install.

Here the log file
![Capture d’écran de 2021-12-03 13-34-21](https://user-images.githubusercontent.com/95325645/144603967-0b1999e3-fe05-45ca-b4b9-ee0bba634cf6.png)

Do you understand something ?

I try to find on my side.

Rgds,

Xavier

**Comment by xlhuillier** [comment]
More details :

Actually, I installed the latest code. I found in python_classes/resources/resource_utils.py that you changed the directory path assignment.
But I have problem in the activation of the add-on.

The issue is that in python_classes/nodes/sockets/property_socket.py, ConstantProperty is called but not found.

I would like to help further more, but I am newbee in Python.

Rgds,

Xav

**Comment by xlhuillier** [comment]
I got the leaves !!

I did not install properly I guess.
I will play with it.

As far as I understand, there is only one leave style and not so much parameter. 
I would really enjoy to participate in making procedural leaves... But I am not strong enough. Could it be listing leave parameters ? Designing differents leaf on Blender ?

Anyhow great job ! Thx a lot

**Comment by MaximeHerpin** [comment]
I'm glad it works !

For the leaves and twigs I was thinking of making them using the geometry nodes (probably for blender 3.0 and above)
