### ISSUE TITLE
cmake on w10

### ISSUE THREAD

**Issue by Marco105** [MaximeHerpin/modular_tree#313]
hello,
I try your new addon, I have a lot difficulty to run CMAKE,
also a lot of error, but it is neccessary to run it ?

Last one is:
```
vcpkg was unable to detect the active compiler's information
```

**Comment by MaximeHerpin** [comment]
Hi, if you just want to use the addon within blender, you just have to [download the zip from the latest release](https://github.com/MaximeHerpin/modular_tree/releases) and install it as you would any blender addon.

you only need cmake and a compiler if you want to develop the addon !

**Comment by Marco105** [comment]
TY, I was in trouble for nothing...
