### ISSUE TITLE
Presets

### ISSUE THREAD

**Issue by ekaj2** [MaximeHerpin/modular_tree#66]
Please post your presets here, and I will check them over and include them if possible. 

To get to your presets, go to the folder where blender is on your system...then go to something like:

~/Blender/2.77/scripts/addons/mod_tree_presets/MyPresetName.mtp

Open that folder and add a comment here.

Please use the format:

```
MyPresetName
========================

paste ENTIRE preset file here...

========================

and any notes you would like to include...
```

**Comment by ekaj2** [comment]
I guess no one wants to help :(

**Comment by MaximeHerpin** [comment]
I will as soon as I find some time, don't worry !

**Comment by ekaj2** [comment]
I wasn't talking about you...I had mentioned this in the BA thread a while ago, but I guess no one there has a GitHub account. If you do it, you can just add it right in with a commit :-)
