### ISSUE TITLE
Images For Wiki Docs

### ISSUE THREAD

**Issue by ekaj2** [MaximeHerpin/modular_tree#86]
[This is an interesting way to add images to the wiki without putting them in the repo.](http://solutionoptimist.com/2013/12/28/awesome-github-tricks/) I am working on adding a much needed documentation here so this is a big help!

![tree-2](https://cloud.githubusercontent.com/assets/20780097/18015349/59b19df0-6b95-11e6-8a19-89bce333c767.jpg)

![tree-2](https://cloud.githubusercontent.com/assets/20780097/18015480/e5ecbeb2-6b95-11e6-9237-1e098740225b.jpg)

<img width="277" alt="make_tree_panel" src="https://cloud.githubusercontent.com/assets/20780097/18015723/d766b176-6b96-11e6-800f-2faa027f3bba.png">

<img width="119" alt="make_tree_panel" src="https://cloud.githubusercontent.com/assets/20780097/18015833/65813f8a-6b97-11e6-9f46-a3cad4e20ebe.png">

**Comment by ekaj2** [comment]
![iterations_demo](https://cloud.githubusercontent.com/assets/20780097/18028328/e7f4da1e-6c49-11e6-8745-7a8fbc0eaaed.png)

![radius_demo](https://cloud.githubusercontent.com/assets/20780097/18028359/b28114c8-6c4a-11e6-97e8-650306fcd087.png)

**Comment by ekaj2** [comment]
![break_chance_demo](https://cloud.githubusercontent.com/assets/20780097/18028915/81d380ec-6c57-11e6-92ab-04b7fb02d9a2.png)

![branch_length_demo](https://cloud.githubusercontent.com/assets/20780097/18028992/75c0a0f8-6c59-11e6-9749-701a05e00a28.png)

![branch_variation_demo](https://cloud.githubusercontent.com/assets/20780097/18029012/1ee01650-6c5a-11e6-93f0-fd981769d32b.png)

![branch_splitprob_demo](https://cloud.githubusercontent.com/assets/20780097/18029029/d4c47c54-6c5a-11e6-810f-d38fd1d461af.png)

**Comment by ekaj2** [comment]
![radius_decrease_demo](https://cloud.githubusercontent.com/assets/20780097/18030486/667d0b8c-6c85-11e6-9d57-3bbe5bbe384c.png)

![branch_split_angle_demo](https://cloud.githubusercontent.com/assets/20780097/18030546/d93bbf5a-6c86-11e6-83c3-41e33f62693d.png)

**Comment by ekaj2** [comment]
![branch_rotation_angle](https://cloud.githubusercontent.com/assets/20780097/18030611/18c89a1e-6c8a-11e6-8bbe-e61e2c2299ad.gif)

![branch_random_rotation_angle](https://cloud.githubusercontent.com/assets/20780097/18030631/e1dbb30a-6c8a-11e6-845b-376d1f79880a.gif)

**Comment by ekaj2** [comment]
![gravity_strength_demo](https://cloud.githubusercontent.com/assets/20780097/18030653/f590e572-6c8b-11e6-9ab6-55e764124a78.png)

**Comment by ekaj2** [comment]
I am closing this issue to get it out of the issue cue. This is still where to put the images.

**Comment by MaximeHerpin** [comment]
![roots node](https://user-images.githubusercontent.com/15239308/29166393-795c99fe-7dc6-11e7-9c0a-ab3dc30d164a.PNG)

![use node worflow](https://user-images.githubusercontent.com/15239308/29166564-36a7ea22-7dc7-11e7-8457-7d1b816524ab.PNG)

![create node tree](https://user-images.githubusercontent.com/15239308/29166753-fa2dee2e-7dc7-11e7-8582-d836a637c2b1.PNG)

![select node tree](https://user-images.githubusercontent.com/15239308/29166914-99a6d0ec-7dc8-11e7-8c85-d4210951906d.PNG)

![setup node tree operator](https://user-images.githubusercontent.com/15239308/29167035-282c4432-7dc9-11e7-8db5-f69f66cd6983.PNG)

![trunk node](https://user-images.githubusercontent.com/15239308/29167801-331cf474-7dcc-11e7-852a-f937e15d04e2.PNG)

![branches node](https://user-images.githubusercontent.com/15239308/29168425-19a0dbd4-7dcf-11e7-9bc2-af8c286ad9f6.PNG)

![tree output node](https://user-images.githubusercontent.com/15239308/29170266-fec954c2-7dd7-11e7-81a0-d50b33c63f5d.PNG)

![curve mapping node](https://user-images.githubusercontent.com/15239308/29171064-7505b588-7ddb-11e7-8081-55fe89026cd8.PNG)

![input iteration](https://user-images.githubusercontent.com/15239308/29171298-58e637b4-7ddc-11e7-848c-157e6670ea62.PNG)

![input radius](https://user-images.githubusercontent.com/15239308/29171477-002dc42e-7ddd-11e7-91b5-d3730a70a7a0.PNG)

![input height](https://user-images.githubusercontent.com/15239308/29171648-82a63e5e-7ddd-11e7-8a79-eb2c7aafa6d4.PNG)

**Comment by MaximeHerpin** [comment]
![tree shape](https://user-images.githubusercontent.com/15239308/29173895-f2ef53e2-7de4-11e7-9495-fee9f3f9b20d.gif)

![finish trunk](https://user-images.githubusercontent.com/15239308/29173950-200ccc42-7de5-11e7-9b78-32e390742997.gif)

**Comment by MaximeHerpin** [comment]
![obstacle node](https://user-images.githubusercontent.com/15239308/29212891-1d57ec90-7ea1-11e7-8f31-a37633d2c240.PNG)

![obstacle](https://user-images.githubusercontent.com/15239308/29213514-dc536712-7ea3-11e7-86ea-8e63a85c0cc7.gif)

![particles node](https://user-images.githubusercontent.com/15239308/29215046-c767a6aa-7ea9-11e7-8868-dae3802a1af1.PNG)

![particles](https://user-images.githubusercontent.com/15239308/29215839-e182d9f8-7eac-11e7-9150-32e7046626b0.gif)

![pruning node](https://user-images.githubusercontent.com/15239308/29218870-90bce2d4-7eb6-11e7-9b07-561d3dfa8d05.PNG)

![pruning](https://user-images.githubusercontent.com/15239308/29220660-108c7768-7ebc-11e7-89dd-f6eab7d0e311.gif)

![armature node](https://user-images.githubusercontent.com/15239308/29220845-ae64d408-7ebc-11e7-9686-c01e06cbf466.PNG)

**Comment by MaximeHerpin** [comment]
![add_node](https://user-images.githubusercontent.com/15239308/38162286-a2af0614-34de-11e8-9230-e1456527398e.jpg)

**Comment by MaximeHerpin** [comment]
![tree tools](https://user-images.githubusercontent.com/15239308/38162363-06b4c544-34e0-11e8-8fc8-91e7aea640ba.JPG)

**Comment by MaximeHerpin** [comment]
![color sampler tool](https://user-images.githubusercontent.com/15239308/38162385-9e6c1432-34e0-11e8-8b04-8a0e9623fc01.JPG)

**Comment by MaximeHerpin** [comment]
![tree tools](https://user-images.githubusercontent.com/15239308/38162932-18ee2c90-34eb-11e8-9b14-4f3118c77313.JPG)

**Comment by MaximeHerpin** [comment]
![trunk_node](https://user-images.githubusercontent.com/15239308/38162935-2b752f58-34eb-11e8-8a49-d6161b614441.JPG)

**Comment by MaximeHerpin** [comment]
![grease_pencil_node](https://user-images.githubusercontent.com/15239308/38163041-9e7e8db2-34ed-11e8-9bfa-b6aefbf44275.JPG)

**Comment by MaximeHerpin** [comment]
![grease_pencil_before](https://user-images.githubusercontent.com/15239308/38163179-dd17a25a-34ef-11e8-89bc-8581ddddfdc3.JPG)
![grease_pencil_after](https://user-images.githubusercontent.com/15239308/38163180-e014e9d6-34ef-11e8-80c9-f16e82a3bf6b.JPG)

**Comment by MaximeHerpin** [comment]
![branch_split](https://user-images.githubusercontent.com/15239308/38163284-f6ae3bb4-34f1-11e8-869a-41ed677e98d6.jpg)

**Comment by MaximeHerpin** [comment]
![splits node](https://user-images.githubusercontent.com/15239308/38163318-52336cd4-34f2-11e8-8330-c88878178aa3.JPG)

**Comment by MaximeHerpin** [comment]
![splits node](https://user-images.githubusercontent.com/15239308/38163324-705647ae-34f2-11e8-9e42-86b65a27ec6d.png)

**Comment by MaximeHerpin** [comment]
![grow_node](https://user-images.githubusercontent.com/15239308/38163391-d544dac6-34f3-11e8-9c64-eb46933cba43.png)

**Comment by MaximeHerpin** [comment]
![preview](https://user-images.githubusercontent.com/15239308/38163738-34e4c446-34f9-11e8-986d-a0d11cf96fa3.PNG)

**Comment by MaximeHerpin** [comment]
![final](https://user-images.githubusercontent.com/15239308/38163872-5d20a6ee-34fb-11e8-9a96-f76c23e55d27.png)

**Comment by MaximeHerpin** [comment]
![build tree](https://user-images.githubusercontent.com/15239308/38163970-27a83d5e-34fd-11e8-8a46-2a7b40a5d092.PNG)

**Comment by MaximeHerpin** [comment]
![armature](https://user-images.githubusercontent.com/15239308/38164180-99e2722e-3500-11e8-8c9e-9b9c72b48cf2.PNG)

**Comment by MaximeHerpin** [comment]
![fast_wind](https://user-images.githubusercontent.com/15239308/38165841-5ace2a00-351a-11e8-95a5-2bf79257ae23.gif)

**Comment by MaximeHerpin** [comment]
![wind_panel](https://user-images.githubusercontent.com/15239308/38165875-0ddb51cc-351b-11e8-8687-b058e0ac5366.png)

**Comment by MaximeHerpin** [comment]
![procedural bark examples](https://user-images.githubusercontent.com/15239308/38427501-afd52938-39b9-11e8-8779-0c8a6d4cf27e.jpg)

**Comment by MaximeHerpin** [comment]
![bark_displace_1](https://user-images.githubusercontent.com/15239308/38428281-ba633d48-39bb-11e8-912a-acd7dc058216.PNG)
![bark_displace_2](https://user-images.githubusercontent.com/15239308/38428284-bc01dbc8-39bb-11e8-86b5-806f09c2a9d4.PNG)

**Comment by MaximeHerpin** [comment]
![twig_operator](https://user-images.githubusercontent.com/15239308/38429088-b6d0b74e-39bd-11e8-973a-f24a8c92901f.PNG)
